"use client";
import { useCallback, useEffect, useState, useTransition } from "react";
import { Check, FileText, Plus, Save, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { DocumentRecord, ProjectTask } from "@/types/domain";

type Detail = { task: ProjectTask; labels: Array<{id:string;name:string;color:string}>; members: Array<{id:string;member_name:string;role:string}>; checklists: Array<{id:string;title:string}>; items: Array<{id:string;checklist_id:string|null;content:string;done:boolean}>; comments: Array<{id:string;author_name:string|null;content:string;created_at:string}>; attachments: Array<{id:string;document_id:string|null;file_name:string;documents?:{status:string}|null}> };
export function TaskCardPanel({ projectId, taskId, documents, onClose, onChange }: { projectId:string; taskId:string; documents:DocumentRecord[]; onClose:()=>void; onChange:()=>void }) {
 const [data,setData]=useState<Detail|null>(null), [error,setError]=useState(""), [pending,start]=useTransition(); const [label,setLabel]=useState(""), [labelColor,setLabelColor]=useState("#0ea5e9"), [member,setMember]=useState(""), [comment,setComment]=useState(""), [item,setItem]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const r=await fetch(`/api/projects/${projectId}/tasks/${taskId}`);const j=await r.json();if(r.ok)setData(j.data);else setError(j.error||"Falha ao abrir card.");},[projectId,taskId]); useEffect(()=>{load();},[load]);
 const act=(payload:Record<string,unknown>, onSuccess?:()=>void)=>start(async()=>{setError("");const r=await fetch(`/api/projects/${projectId}/tasks/${taskId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){setError(j.error||"Não foi possível salvar.");return;}setData(j.data);onChange();onSuccess?.();});
 if(!data) return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4"><div className="rounded-2xl border border-white/10 bg-slate-900 p-6 text-slate-200">{error||"Carregando card..."}</div></div>;
 const {task}=data; const listItems=(id:string)=>data.items.filter(x=>x.checklist_id===id); const linked=new Set(data.attachments.map(x=>x.document_id));
 return <div className="fixed inset-0 z-50 bg-slate-950/80 p-3 sm:p-6"><section className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden rounded-3xl border border-cyan-300/20 bg-slate-950 shadow-2xl"><header className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-200">Atividade do projeto</p><p className="text-sm text-slate-400">Edite e acompanhe tudo sem sair do workspace.</p></div><Button variant="secondary" size="sm" onClick={onClose}><X className="h-4 w-4"/>Fechar</Button></header><div className="overflow-y-auto p-5"><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><Input defaultValue={task.titulo} onBlur={e=>e.target.value!==task.titulo&&act({action:"update",titulo:e.target.value})} className="text-lg font-semibold"/><Textarea defaultValue={task.descricao||""} onBlur={e=>e.target.value!==(task.descricao||"")&&act({action:"update",descricao:e.target.value})} placeholder="Descreva o objetivo, critérios de aceite e próximos passos."/><div className="grid grid-cols-2 gap-3"><select defaultValue={task.prioridade} onChange={e=>act({action:"update",prioridade:e.target.value})} className="rounded-xl border border-white/10 bg-slate-900 px-3 text-sm text-white"><option value="LOW">Prioridade baixa</option><option value="MEDIUM">Prioridade média</option><option value="HIGH">Prioridade alta</option><option value="CRITICAL">Prioridade crítica</option></select><Input type="date" defaultValue={task.prazo||""} onBlur={e=>act({action:"update",prazo:e.target.value||null})}/></div><Input defaultValue={task.responsavel||""} onBlur={e=>act({action:"update",responsavel:e.target.value||null})} placeholder="Responsável principal"/>
 <Block title="Etiquetas"><div className="flex flex-wrap gap-2">{data.labels.map(x=><button key={x.id} onClick={()=>act({action:"remove_label",labelId:x.id})} className="rounded-full px-2 py-1 text-xs text-white" style={{background:x.color}}>{x.name} ×</button>)}</div><div className="mt-2 flex items-center gap-2"><Input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Nova etiqueta"/><input aria-label="Cor da etiqueta" type="color" value={labelColor} onChange={e=>setLabelColor(e.target.value)} className="h-9 w-11 cursor-pointer rounded border border-white/10 bg-slate-900 p-1"/><Button size="sm" disabled={!label.trim()||pending} onClick={()=>act({action:"add_label",labelName:label,color:labelColor},()=>setLabel(""))}><Plus className="h-4 w-4"/></Button></div></Block>
 <Block title="Checklists">{data.checklists.map(list=><div key={list.id} className="mb-3 rounded-xl border border-white/10 p-3"><p className="font-medium text-white">{list.title}</p>{listItems(list.id).map(i=><label key={i.id} className="mt-2 flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={i.done} onChange={e=>act({action:"toggle_checklist_item",itemId:i.id,done:e.target.checked})}/><span className={i.done?"line-through text-slate-500":""}>{i.content}</span></label>)}<div className="mt-2 flex gap-2"><Input value={item[list.id]||""} onChange={e=>setItem({...item,[list.id]:e.target.value})} placeholder="Novo item"/><Button size="sm" onClick={()=>{if(item[list.id]){act({action:"add_checklist_item",checklistId:list.id,content:item[list.id]});setItem({...item,[list.id]:""})}}}><Plus className="h-4 w-4"/></Button></div></div>)}<Button size="sm" variant="secondary" onClick={()=>act({action:"add_checklist",checklistTitle:"Checklist"})}><Plus className="h-4 w-4"/>Adicionar checklist</Button></Block>
 <Block title="Comentários">{data.comments.map(c=><div key={c.id} className="mb-2 rounded-xl bg-white/5 p-3 text-sm"><p className="text-cyan-200">{c.author_name||"Você"}</p><p className="mt-1 text-slate-200">{c.content}</p></div>)}<div className="flex gap-2"><Textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Registre uma atualização..."/><Button disabled={!comment.trim()||pending} onClick={()=>{act({action:"add_comment",content:comment});setComment("")}}><Save className="h-4 w-4"/></Button></div></Block></div>
 <aside className="space-y-5"><Block title="Participantes">{data.members.map(m=><button key={m.id} onClick={()=>act({action:"remove_member",memberId:m.id})} className="mb-2 block rounded-lg bg-white/5 px-3 py-2 text-left text-sm text-slate-200">{m.member_name} <span className="text-slate-500">· {m.role} · remover</span></button>)}<div className="flex gap-2"><Input value={member} onChange={e=>setMember(e.target.value)} placeholder="Nome do participante"/><Button size="sm" onClick={()=>{if(member){act({action:"add_member",memberName:member});setMember("")}}}><Plus className="h-4 w-4"/></Button></div></Block><Block title="Documentos vinculados">{data.attachments.map(a=><div key={a.id} className="mb-2 flex items-center gap-2 text-sm text-slate-300"><FileText className="h-4 w-4 text-cyan-200"/>{a.file_name}</div>)}<select className="w-full rounded-xl border border-white/10 bg-slate-900 p-3 text-sm text-white" defaultValue="" onChange={e=>e.target.value&&act({action:"link_document",documentId:e.target.value})}><option value="">Vincular documento do projeto</option>{documents.filter(d=>!linked.has(d.id)).map(d=><option key={d.id} value={d.id}>{d.nome_arquivo} · {d.status}</option>)}</select></Block><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-3 text-xs text-slate-300"><Check className="mb-2 h-4 w-4 text-cyan-200"/>As alterações ficam registradas no card e só podem usar documentos deste projeto.</div>{error&&<p className="text-sm text-red-300">{error}</p>}</aside></div></div></section></div>;
}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/10 bg-slate-900/45 p-4"><h3 className="mb-3 font-semibold text-white">{title}</h3>{children}</section>}
