insert into knowledge_taxonomies (scope, code, label, sort_order, active) values
  ('instructions', 'PERFIL_PROFISSIONAL', 'Perfil Profissional', 1, true),
  ('instructions', 'PROJETOS', 'Projetos', 2, true),
  ('instructions', 'TECNOLOGIA', 'Tecnologia', 3, true),
  ('instructions', 'COMUNICACAO', 'Comunicação', 4, true),
  ('instructions', 'DECISAO', 'Decisão', 5, true),
  ('instructions', 'GESTAO', 'Gestão', 6, true),
  ('instructions', 'IA', 'IA', 7, true),
  ('instructions', 'PESSOAL', 'Pessoal', 8, true),
  ('instructions', 'EAC', 'EAC', 9, true),
  ('memories', 'PERSONAL', 'PERSONAL', 1, true),
  ('memories', 'PROFESSIONAL', 'PROFESSIONAL', 2, true),
  ('memories', 'TECHNICAL', 'TECHNICAL', 3, true),
  ('memories', 'PROCESS', 'PROCESS', 4, true),
  ('memories', 'DECISION', 'DECISION', 5, true),
  ('memories', 'PREFERENCE', 'PREFERENCE', 6, true),
  ('memories', 'PROJECT', 'PROJECT', 7, true),
  ('memories', 'CLIENT', 'CLIENT', 8, true),
  ('memories', 'EAC', 'EAC', 9, true),
  ('documents', 'PROJETOS', 'Projetos', 1, true),
  ('documents', 'NEGOCIOS', 'Negocios', 2, true),
  ('documents', 'IA', 'IA', 3, true),
  ('documents', 'PESSOAL', 'Pessoal', 4, true),
  ('documents', 'EAC', 'EAC', 5, true),
  ('documents', 'TECNOLOGIA', 'Tecnologia', 6, true),
  ('documents', 'CONTRATOS', 'Contratos', 7, true),
  ('documents', 'ATAS', 'Atas', 8, true),
  ('documents', 'ARQUITETURAS', 'Arquiteturas', 9, true),
  ('documents', 'ESTUDOS', 'Estudos', 10, true)
on conflict (scope, code) do update
set label = excluded.label,
    sort_order = excluded.sort_order,
    active = excluded.active,
    updated_at = now();

